sudo: required
services:
  - docker
before_install:
  - ENV CHROME_BIN=/usr/bin/google-chrome
  - docker build -t surath/sample-app -f Dockerfile.dev .
script:
  - docker run surath/sample-app npm run test
