sudo: required
services:
  - docker
before_install:
  - export CHROME_BIN=chromium-browser
  - docker build -t surath/sample-app -f Dockerfile.dev .
script:
  - docker run -e CI=true surath/sample-app npm run test
